# Generated by Django 3.0.2 on 2020-02-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_choice_post_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
